In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3])

In [3]:
print(array.size)
print(array.dtype)
print(array[2])                          #주의! Index는 0부터 시작

3
int32
3


In [4]:
array1 = np.arange(4)                   # np.array(range(4))를 줄인것
print(array1)

[0 1 2 3]


In [5]:
array2 = np.zeros((4, 4), dtype=float) # 4 x 4 행렬인데 원소가 전부 0
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
array3 = np.ones((3, 3), dtype=str)    # 3 x 3 행렬인데 원소가 전부 '1'(문자)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [7]:
array4 = np.random.randint(0, 10, (3, 3))   # 0부터 (10-1) 사이의 랜덤한 숫자가 원소
print(array4)

[[5 3 4]
 [2 6 3]
 [5 3 9]]


In [8]:
array5 = np.random.normal(0, 1, (3, 3))    # 0이 평균, 표준편차가 1인 랜덤한 숫자 원소가 표준 분포를 띄움
print(array5)

[[ 0.90007946  0.26650155 -0.33322651]
 [-1.67438887  0.56941938 -1.9114067 ]
 [ 0.71198796 -0.06842915  0.71125857]]


In [9]:
array1 = np.array([1, 2, 3])                # 바로 위 array1 덮어씌움
array2 = np.array([4, 5, 6])                # 바로 위 array2 덮어씌움
array3 = np.concatenate([array1, array2])   # 열방향(좌우)으로 이어 붙이는 Concatenate
print(array3.shape)                         
print(array3)                               # 1 x 6 형태로 이어짐

(6,)
[1 2 3 4 5 6]


In [10]:
array1 = np.array([1, 2, 3, 4])             
array2 = array1.reshape((2, 2))             # 행렬을 2 x 2 행렬로 모양 변경
print(array2.shape)                         # 순서대로 원소를 넣었다 "[1,2]; [3,4]"

(2, 2)


In [11]:
array1 = np.arange(4).reshape(1, 4)         
array2 = np.arange(8).reshape(2, 4)         # "[0,1,2,3] ; [4,5,6,7]"
print(array1)
print(array2)
array3 = np.concatenate([array1, array2], axis=0)  # axis = 0은 행/열 중 행방향(상하)을 의미
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [12]:
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis=1)         # index 2를 기준(index 0,1 // index 2,3)로 열 쪼개기
print(left)
print(right)
print(right[1][1])

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
7
