In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 10, size=4).reshape(2, 2)    # 4개의 random integer를 원소로 한 1 x 4 행렬을 만들고 2 x 2로 reshape 
array

array([[5, 7],
       [6, 7]])

In [3]:
result_array = array * 10         # 행렬에 스칼라 상수 곱하기
print(result_array)

[[50 70]
 [60 70]]


In [4]:
array1 = np.arange(4).reshape(2, 2)     # [0, 1] ; [2, 3]
array2 = np.arange(2)                   # [0, 1]
array3 = array1 + array2                # 행렬 크기가 안 맞으니 맞춘다 by 행 우선 고로 array2 = [0,1] ; [0,1]

print(array3)

[[0 2]
 [2 4]]


In [5]:
array1 = np.arange(0, 8).reshape(2, 4)             # [0,1,2,3] ; [4,5,6,7]
array2 = np.arange(0, 8).reshape(2, 4)             
array3 = np.concatenate([array1, array2], axis=0)  # [0,1,2,3] ; [4,5,6,7] ; [0,1,2,3] ; [4,5,6,7]
array4 = np.arange(0, 4).reshape(4, 1)             # [0] ; [1] ; [2] ; [3]

print(array3 + array4)                            # 크기 맞출려고 array4가 [0,0,0,0];[1,1,1,1];[2,2,2,2];[3,3,3,3]

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [6]:
array1 = np.arange(16).reshape(4, 4)
print(array1)                               # [0,1,2,3] ; [4,5,6,7] ; [8,9,10,11] ; [12,13,14,15]

array2 = array1 < 10
print(array2)                               #[T,T,T,T];[T,T,T,T];[T,T,F,F];[F,F,F,F]

array1[array2] = 100                       # True 면 100을 반환(Return) 그렇지 않으면 array1 원소
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [7]:
array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))         # 원소의 최대값
print("최소값:", np.min(array))         # 원소의 최소값
print("합계:", np.sum(array))           # 원소들의 합
print("평균값:", np.mean(array))        # 원소들의 평균

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [8]:
array = np.arange(16).reshape(4, 4)

print("합계:", np.sum(array, axis=0))  # 원소들을 행방향으로 합한다 (1 x 4 행렬 만듦)

합계: [24 28 32 36]
