In [1]:
import numpy as np

array = np.arange(0, 10)          # 객체 1개(array 1개)를 저장
np.save('saved.npy', array)       # saved.npy로 저장된 array

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
array_a = np.arange(0, 10)
array_b = np.arange(10, 20)
np.savez('saved.npz', array1=array_a, array2=array_b)   # savez는 여러개 객체 저장, array1에는 array_a를 array2에는 array_b를 저장한다

data = np.load('saved.npz')                             # saved.npz를 불러오고
result1 = data['array1']                                # 불러온 파일의 array1 
result2 = data['array2']                                # 불러온 파일의 array2
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [3]:
array = np.array([5, 9, 10, 3, 1])                # 기본 옵션이 오름차순이다
array.sort()
print(array)

array = np.array([5, 9, 10, 3, 1])                # 다음 행렬[::-1]의  ::-1의 -1부분은 step을 나타낸다(여기서는 거꾸로)
array.sort()                                      # 즉, 내림차순이다
print(array[::-1])


array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])  # axis = 0은 행 방향이므로 두 행렬의 원소 자리의 원소 중 더 작은 값이 위에
array.sort(axis=0)                                     # 더 큰 값이 아래 행렬에 배치된다
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [4]:
array = np.linspace(0, 10, 5)                   # 0이상 10이하를 5등분 하는 linspace
print(array)

np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))         # 결과가 고정되는 난수를 .random.seed(7)  AI에서도 random_state로 난수 고정됨

array1 = np.arange(0, 10)
array2 = array1.copy()                         # 복사
print(array2)

array = np.array([1, 1, 2, 3, 3, 3, 1])        # Unique한 데이터만 남긴다
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
